// <auto-generated />
using System;
using AnimalShelter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimalShelter.Migrations
{
    [DbContext(typeof(AnimalShelterContext))]
    [Migration("20210402175500_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("AnimalShelter.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Admitted")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Species")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Admitted = new DateTime(2021, 4, 2, 10, 55, 0, 421, DateTimeKind.Local).AddTicks(9450),
                            Age = 3,
                            Gender = "Male",
                            Name = "Attila",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 2,
                            Admitted = new DateTime(2021, 4, 2, 10, 55, 0, 421, DateTimeKind.Local).AddTicks(9850),
                            Age = 10,
                            Gender = "Male",
                            Name = "RZA",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 3,
                            Admitted = new DateTime(2021, 4, 2, 10, 55, 0, 421, DateTimeKind.Local).AddTicks(9860),
                            Age = 1,
                            Gender = "Female",
                            Name = "Maple",
                            Species = "Chicken"
                        },
                        new
                        {
                            AnimalId = 4,
                            Admitted = new DateTime(2021, 4, 2, 10, 55, 0, 421, DateTimeKind.Local).AddTicks(9860),
                            Age = 2,
                            Gender = "Female",
                            Name = "Beatrix",
                            Species = "Chicken"
                        },
                        new
                        {
                            AnimalId = 5,
                            Admitted = new DateTime(2021, 4, 2, 10, 55, 0, 421, DateTimeKind.Local).AddTicks(9860),
                            Age = 12,
                            Gender = "Female",
                            Name = "Petunia",
                            Species = "Donkey"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
